- hosts: localhost
  tasks:
  - package:
      name: "apache2"
      state: present
      update_cache: yes
  - package:
      name: "mysql-server"
      state: present
      update_cache: yes
  - name: ensure repository key is installed
    apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
  - name: ensure docker registry is available
    apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

  - name: ensure docker and dependencies are installed
    apt: name=docker-ce update_cache=yes
  - name: Start docker service
    service:
      name: docker
      state: started
